weather:
  api:
    key: ${WWO_KEY}
    # Number of days shown in the response. This will be different from the number of days received
    # from the weather data source
    number-of-days: 3
    humidity-as-decimals: true
    # Mapping between our own DTOs and the data received from the weather data source
    mapping:
      current-weather:
        temp-c: "$.data.current_condition[0].temp_C"
        temp-f: "$.data.current_condition[0].temp_F"
        humidity: "$.data.current_condition[0].humidity"
        description: "$.data.current_condition[0].weatherDesc[0].value"
      # The data in the forecast weather will be represented by an array. We could actuallly skip
      # the first element as that represents the weather for the current day, while we are
      # only interested in the days after today, but for locations that already had
      # a day change we would skip their first day, which actually interests us
      forecast-weather:
        date: "$.data.weather[0:].date"
        temp-c: "$.data.weather[0:].hourly[0].tempC"
        temp-f: "$.data.weather[0:].hourly[0].tempF"
        humidity: "$.data.weather[0:].hourly[0].humidity"
        description: "$.data.weather[0:].hourly[0].weatherDesc[0].value"
        date-format: "yyyy-MM-dd"

cache:
  expire:
    afterH: 1